# Generated by Django 6.0.3 on 2026-03-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_course_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
