# Generated by Django 6.0.3 on 2026-04-01 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_enrollment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
